import Head from "next/head";
import styles from "@/styles/Home.module.css";

import { Button, NavDropdown, Table } from "react-bootstrap";
import { useState } from "react";

import ModalConfirm from "../../components/ModalConfirm";
import Link from "next/link";
import { useDispatch, useSelector } from "react-redux";
import { RootState } from "../store/store";
import { useRouter } from "next/router";
import { removeItem } from "@/store/profileSlice";

export default function Home() {
  const profileList = useSelector((state: RootState) => state.profile);
  const router = useRouter();
  const dispatch = useDispatch();
  const [deleteId, setDeleteId] = useState<number | null>(null);

  const MessageWarningtext: MessagePopup = {
    title: "THIS IS CONFIRM warning",
    detail: "Are you sure to delete ?",
    type: "error",
    afterConfirmType: "success",
    afterConfirmTitle: "Finished !!",
    afterConfirmDetail: "Data is deleted",
    confirmButtonText: "Sure, Delete it!",
  };
  const handleViewProfile = (id: number) => {
    router.push(`/view/${id}`);
  };
  const handleEditProfile = (id: number) => {
    router.push(`/edit/${id}`);
  };
  const handleRemoveProfile = (id: number) => {
    setDeleteId(id);
  };
  return (
    <>
      <Head>
        <title>Example Bootstrap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className={styles.description}>
          <div className="d-flex justify-content-between mb-3">
            {" "}
            <h3 className="text-center">Dashboard</h3>
            <Button className="regis-button">
              <Link href="/create" className="regis-link">
                Register
              </Link>
            </Button>
          </div>

          {/* <Link href="/create">Register</Link>
          <Link href="/view">View</Link>
          <Link href="/edit">edit</Link> */}
          <Table striped bordered hover variant="dark">
            <thead>
              <tr>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">birthday </th>
                <th scope="col">role </th>
                <th scope="col">tel </th>
                <th scope="col">action </th>
              </tr>
            </thead>
            <tbody>
              {profileList.map((profile) => (
                <tr key={profile.id}>
                  <td>{profile.name || "null"}</td>
                  <td>{profile.email || "null"}</td>
                  <td>{profile.birthday || "null"}</td>
                  <td>{profile.role || "null"}</td>
                  <td>{profile.tel || "null"}</td>
                  <td style={{ display: "flex" }}>
                    {" "}
                    <NavDropdown title="action" id="nav-dropdown">
                      <NavDropdown.Item
                        eventKey="4.1"
                        onClick={() => handleViewProfile(profile.id)}
                      >
                        view
                      </NavDropdown.Item>
                      <NavDropdown.Item
                        eventKey="4.2"
                        onClick={() => handleEditProfile(profile.id)}
                      >
                        edit
                      </NavDropdown.Item>
                      <NavDropdown.Divider />
                      <NavDropdown.Item
                        eventKey="4.4"
                        className="text-danger my-auto"
                        onClick={() => handleRemoveProfile(profile.id)}
                      >
                        <ModalConfirm
                          data={deleteId}
                          text={"danger"}
                          onClick={() => {
                            dispatch(removeItem(profile.id));
                          }}
                          MessageConFirmtext={MessageWarningtext}
                        />
                      </NavDropdown.Item>
                    </NavDropdown>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        </div>
      </div>
    </>
  );
}
